### ISSUE TITLE
Some of the songs doesn't work

### ISSUE THREAD

**Issue by DJANDREAJAPAN** [Tzwcard/2dx_gst#1] opened 2020-08-02 00:43 UTC
I tried your 2dx and .1 file gluer, and it works fine.
The only problem is that if I use this tool in the song files at the beatmaniaIIDX INFINITAS folder, some songs have incorrect sound and some doesn't even work.
For the incorrect audio, I found it on "Plan 8" and "New Decade IIDX Edition".
For the Sound Buffer Pool initialize error that this thing doesn't function properly, I found that on "ANTHEM LANDING" and "3y3s (Long Ver)".
If it's possible, would you update this tool to support all IIDX songs with 2dx and .1 files please?
Thanks.

**Comment by DJANDREAJAPAN** [comment] 2020-08-02 01:11
Also, it would be better to make this as an exe file for command prompt.
The reason is because I used this tool by compiling the cpp files on Visual Studio and build it as an exe file, just to use it.

**Comment by DJANDREAJAPAN** [comment] 2020-08-03 20:28
（Update）I changed the sound buffer level from 1024x1024 to 3072x3072, and it kinda worked on some of the songs that couldn't output the song, like 3y3s Long Ver.
But couple of the songs still have incomplete sound when I compile the song data with this tool, so I don't think this tool is complete yet.

**Comment by Tzwcard** [comment] 2022-05-20 17:19
I just realised that you posted an issue here
For the long music(3y3s, ANTHEM LANDING, etc), they should works now since that's caused by not enough buffer size
For other songs such as New Decade I think it's a sample rate issue, might fix it asap

Also it should support the new MSS in iidx29, if you can try to test it

**Comment by Tzwcard** [comment] 2022-05-20 18:19
Okay it should fixed now.
There's 2 .2dx file related errors that I didn't noticed since post-CB are all using s3p, that I didn't know it was broken.

**Closed as completed** 2022-07-15 03:19 UTC
